- name: Check if bootstrap is needed
  raw: stat /root/.bootstrapped
  register: need_bootstrap
  ignore_errors: True

- name: Run bootstrap.sh
  script: bootstrap.sh
  when: need_bootstrap | failed
  become: True

- debug: var=ansible_python_interpreter
